### ISSUE TITLE
Question about development mode

### ISSUE THREAD

**Issue by GhostComputing** [deepfabric/elasticell#9]
It's the interesting project that I have tried the same thing before(base on LogCabin and rocksdb, redis-like API), unfortunately, my project is not going on.

Does it will continue to develop and keep open source by business company(like TiDB or CockroachDB) or use other development mode ？

**Comment by zhangxu19830126** [comment]
We will always open source, and continue to maintain this project. If you are want to use in production, we will provide support.

**Comment by yingfeng** [comment]
LogCabin does not perform well due to being lack of some engineering tricks compared with etcd. You could try [this raft implementation](https://github.com/neverchanje/consensus-yaraft) if you prefer C++. On the other hand, Elasticell is a multi-raft implementation providing cloud native distributed sharded storage instead of single raft.

**Comment by GhostComputing** [comment]
@yingfeng Yes, you're totally right and that's why I give up LogCabin and focus on `etcd/raft`. I plan to build my own KV storage ( base on `etcd/raft`, support redis-like API and use RocksDB as backend storage), then I found your project. The idea of project is very good.
